### ISSUE TITLE
Lolex unable to trigger setTimeout in non-test file

### ISSUE THREAD

**Issue by emfleisch** [sinonjs/lolex#155]
Im using sinon/mocha for my TS test suite. In one non-test file I have a setTimeout cmd with a 90 second timer.  In my test file, i set up a clock with  `const clock = lolex.install()`. 
I can confirm in my test file that any setTimeout or clock call is based off this lolex clock, however the external setTimeout will not get triggered. 
Also confirmed  in my test file that a Date.now() will show the actual system clock not the lolex clock time. 

I upgraded from sinon 1.17.0 to 4.1.6 and this started happening. 
Node:8.9.3
TS 2.6.2
Sinon - 4.1.6
Lolex - 2.3.2

**Comment by fatso83** [comment]
We need actual reproducible code for this to be checked out. Can you make a minimal test case that we can run? JSBIN, a repo, a gist, something?

**Comment by vekexasia** [comment]
Experienced this issue too apparently `global.setTimeout.toString()` returns the `lolex` rewritten `setTimeout` while `setTimeout.toString()` returns the original setTimeout code.

How that is possible is out of my current understanding.

Cc: @mcanever

**Comment by fatso83** [comment]
@vekexasia can you make a reproducible snippet? That makes it far more likely someone will take a look at it.

**Comment by vekexasia** [comment]
Hey: 

https://github.com/RiseVision/rise-node/blob/feature/typescript-matteo/src/modules/forge.ts#L98-L112

cannot be tested with sinon useFakeTimers.

One of many trials to properly test it is here:
https://github.com/RiseVision/rise-node/blob/feature/typescript-matteo/tests/unit/modules/forge.spec.ts#L253-L260

**Comment by fatso83** [comment]
@vekexasia I have checked out the code and run the test. Indeed, while the test has `global.setTimeout === setTimeout` it is false when running actual production code.

Do you need if this worked at a point?

I was fairly confident this had something to do with cached references in the transpiled output, but your project's build script failed every time due to some typescript bug with `@types/colors` not maching, so I couldn't inspect the transpiled output. 

What I did was stuffing [the relevant bits of the code into a transpiler](https://www.typescriptlang.org/play/#src=async%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%2F%2Fdebugger%3B%0D%0A%20%20%20%20%20%20%20%20console.log('%23%23test%23%23')%0D%0A%20%20%20%20%20%20%20%20console.log(setTimeout.toString())%0D%0A%20%20%20%20%20%20%20%20console.log(global.setTimeout.toString())%0D%0A%20%20%20%20console.log(global.setTimeout%20%3D%3D%20setTimeout)%0D%0A%20%20%20%20%20%20%20%20%0D%0A%20%20%20%20%20%20%20const%20p%20%3D%20instance.onBlockchainReady()%3B%0D%0A%20%20%20%20%20%20%20expect(jobsQueueStub.stubs.register.notCalled).to.be.true%3B%0D%0A%20%20%20%20%20%20%20clock.tick(10100)%3B%0D%0A%20%20%20%20%20%20%20await%20p%3B%0D%0A%20%20%20%20%20%20%20%20console.log('%23%23test%20end%23%23')%0D%0A%20%20%20%20%20%20%20expect(jobsQueueStub.stubs.register.called).to.be.true%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0A%20%20async%20function%20onBlockchainReady()%20%7B%0D%0A%20%20%20%20console.log('%23%23%23onBlockchainReady')%0D%0A%20%20%20%20%20%20debugTimeout()%3B%0D%0A%20%20%20%20console.log('%23%23%23%20onBlockchainReady%20end')%0D%0A%20%20%20%20setTimeout(%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('onBlockchainReady%20in%20setTimeout')%0D%0A%20%20%20%20%20%20this.jobsQueue.register(%0D%0A%20%20%20%20%20%20%20%20'delegatesNextForge'%2C%0D%0A%20%20%20%20%20%20%20%20async%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20try%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20await%20this.transactionsModule.fillPool()%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20await%20this.forge()%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%7D%20catch%20(err)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.logger.warn('Error%20in%20nextForge'%2C%20err)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%201000)%3B%0D%0A%20%20%20%20%7D%2C%2010000)%3B%20%2F%2F%20Register%20forging%20routine%20after%2010seconds%20that%20blockchain%20is%20ready.%0D%0A%20%20%7D%0D%0A) to see what the equivalent ES5 code looked like.

I really couldn't tell ... There was no implicit caching of setTimeout I could see that would explain this. But we still don't really have a simple, reproducible case showing this as a bug in `sinon` so far. Just some code that after transpilation fails to work, so I am not yet 100% confident this is a bug in Sinon. Having used a bit too much time trying to inspect it, without seeing anything relevant, I'll let this one lie for someone else to pick up.

**Comment by fatso83** [comment]
@emfleisch Are you able to produce a simple, runnable example? Preferably without a transpilation step that obscures what is going on. It could be ESNext, as long as it runs in some version of Node or Chrome.

**Comment by vekexasia** [comment]
Apparently it's due `rewire` The tested module is loaded using `rewire`.

**Comment by benjamingr** [comment]
Stale and not a bug :) Thanks for the report!
