### ISSUE TITLE
Feature: isomorphic now() API for browser and node

### ISSUE THREAD

**Issue by dbkaplun** [sinonjs/lolex#182]
Hello,

It would be great if lolex included a `now` function that uses `hrtime` in Node and `performance.now` in the browser. Platform-agnostic code would be easier to write and test in this case.

Thanks for considering!

**Comment by benjamingr** [comment]
@dbkaplun we (Node.js) ship [performance.now](https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_now) now - you can use that as far as I know.

Also note that lolex is used to deal with existing browser APIs so I'm not sure if it would be our place to add an API. 

Thanks for opening an issue!

**Comment by dbkaplun** [comment]
Ah okay, then perhaps the documentation [should be changed](https://github.com/sinonjs/lolex#clockperformancenow) to reflect that. Right now, it says
> Only available in browser environments, mimicks performance.now().

Also, FWIW, current Node LTS (v8) does not seem to have it yet. (Although I look forward to it in a future upgrade.)

**Comment by benjamingr** [comment]
That's because Node.js's performance is still an experimental API and no one asked for `performance.now` to work there. So [when we added it](https://github.com/sinonjs/lolex/pull/106) we didn't add support.

I [did open a follow up](https://github.com/sinonjs/lolex/issues/128) but the work never got done. No one has asked for this yet.

So I guess it's currently blocked on the fact no one uses it and lolex yet 😅

**Comment by benjamingr** [comment]
@SimenB yeah totally it's more of a "no one asked for this" than a "we can't do it".
