### ISSUE TITLE
TypeScript definition files

### ISSUE THREAD

**Issue by benjamingr** [sinonjs/lolex#220]
@zyishai has volunteered to help work on updating the TypeScript types of lolex to a point where they are up to date with recent additions.

Currently we don't ship TypeScript types with the library and people get them from DefinitelyTyped through @types/lolex here https://www.npmjs.com/package/@types/lolex 

I'm wondering if it makes sense to move the types to the lolex repo so we can better keep them in sync  - it could also save an `npm install` for those users if we just provide a `.d.ts` for lolex.

I'm in favour of adding them here and hopefully migrate (properly and with attribution!) content from the definitely typed repo at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c61b1db6eb1d45546d6e88af964d10f73aed309b/types/lolex/index.d.ts

cc @fatso83 @SimenB  what do you think?

**Comment by zyishai** [comment]
@benjamingr I'll be glad to contribute! I'm still beginning my TS journey, hope I'll be able to help!

**Comment by SimenB** [comment]
FWIW, I use TS at work, but I don't use Lolex at work (and if we do at some point, it'll be through using it with Jest, so typing info for it wouldn't matter for us).

As long as we set up some build step that checks that the TS file is in sync with reality I'm all for adding it. I guess it's easier to keep up to date here.

Since TS supports jsdoc, we could also in theory type up our source code with comments and generate the declaration file as a build step. Not sure if we want that or not, though 🙂

**Comment by mgred** [comment]
> I'm wondering if it makes sense to move the types to the lolex repo

Totally! The argument of saving users from having another dependency is super solid, in my opinion.

> I'm in favour of adding them here and hopefully migrate (properly and with attribution!) content from the definitely typed repo at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c61b1db6eb1d45546d6e88af964d10f73aed309b/types/lolex/index.d.ts

That's quite a good start :+1: 

> As long as we set up some build step that checks that the TS file is in sync with reality I'm all for adding it

That would be really awsome

> Since TS supports jsdoc, we could also in theory type up our source code with comments and generate the declaration file as a build step.

Nice idea, commenting types in code is always nice for unferstanding, I think. If we could benefit from that in terms of generating definitions files, that would be win-win.

I used to use TS at work a lot, so if any questions or task raise here, I'll try to help.

**Comment by zyishai** [comment]
OK, just finished updating the types to version 3! for now, I opened PR to DefinitelyTyped. If you decide in the future that you want to include ts in this repo - feel free to tell me and I will PR here too 😊.
cc @benjamingr

**Comment by benjamingr** [comment]
Thanks and awesome work! Let's see how the DT PR goes and close this when it lands :)

**Comment by SimenB** [comment]
Since this happened, Jest has been migrated to TS, so it's suddenly more interesting to me personally for the the typings file to live in this repo...
Main benefit to keeping it here rather than DT would be better autocomplete for everybody (at least if they use vs code or webstorm, probably more IDEs as well) regardless if they use TS or not

**Comment by benjamingr** [comment]
@SimenB I'm up for it

**Comment by DominicTobias-b1** [comment]
Hi, are there typings now? Think I'll have to switch back to sinon main lib for typings

**Comment by SimenB** [comment]
current status: https://github.com/sinonjs/fake-timers/pull/293#issuecomment-581890712

**Comment by fatso83** [comment]
@DominicTobias-b1 we started shipping typings with v7
